### ISSUE TITLE
Generic methods and functions aren't highlighted correctly

### ISSUE THREAD

**Issue by mhmdanas** [dart-lang/dart-vim-plugin#105]
```dart
// Generic classes are highlighted correctly
class Box<T> {
  final T value;

  Box(this.value);

  // Generic methods are not
  Box<U> map<U>(U Function(T) f) => Box(f(value));
}

// This also happens at call site
final foo = Box(5).map((x) => x.toString());
final bar = Box(5).map<String>((x) => x.toString());

// It also happens in normal functions
void myPrint<T>(T value) {
  print(value);
}

myPrint('hello');
myPrint<String>('hello');
```
![Screenshot](https://user-images.githubusercontent.com/32234660/78747755-d9786480-7972-11ea-81ae-8a62274cc613.png)

**Comment by natebosch** [comment]
function highlighting is pretty new and not super robust - it's based on lowercase name followed by the opening paren. We do allow whitespace in between - I'm not entirely sure why.

Since this is a regex match I don't know how robustly we can ignore the generic arguments - they could be nested arbitrarily deeply and they include commas and spaces, maybe even newlines.

If someone wants to take a try at updating this it's here:

https://github.com/dart-lang/dart-vim-plugin/blob/4375ab9cc1fe0077c36a9aba5dd7145ce4a2fa6f/syntax/dart.vim#L58

My suspicion is that to make it work we may need to use a `contains` or something, but I'm not entirely sure.

PRs are welcome.
