### ISSUE TITLE
Support for Asynchronous Lint Engine

### ISSUE THREAD

**Issue by ram535** [dart-lang/dart-vim-plugin#39]
Is it possible to add support for Asynchronous Lint Engine?
https://github.com/w0rp/ale
Thanks

**Comment by natebosch** [comment]
I think the `ale` model is to build support for languages within the plugin rather than to have hooks to add support for languages.

You probably want to file an issue against ale asking for it to support the `dartanalyzer` binary. You can point them at the [`dart#analyzer`](https://github.com/dart-lang/dart-vim-plugin/blob/d60ed814030f0b0279a050725f70b8d00f039976/autoload/dart.vim#L46) function which I think give enough info on usage.
