### ISSUE TITLE
how to indent 2 space, when I press enter

### ISSUE THREAD

**Issue by MonkeyInWind** [dart-lang/dart-vim-plugin#75]
I set dart_style_guide = 2, but it auto indent 4 space when I Pressed Enter.
![image](https://user-images.githubusercontent.com/34543887/51681753-8d1c5f80-2020-11e9-8f15-29280e37b8f6.png)

**Comment by MonkeyInWind** [comment]
![image](https://user-images.githubusercontent.com/34543887/51682030-51ce6080-2021-11e9-8cef-66a0b76d9fd6.png)
here
I pressed enter it auto indent 8 space

**Comment by natebosch** [comment]
The 4 space indent in the constructor call is intentional. This matches `dartfmt` _except_ in the cases where you use a trailing comma in the argument list.

I'm not sure what's going on with the 8 space indent, I think it might have to do with the fact that there are 2 opening parens on line 3 and so we get into some nesting paren behavior. `dartmft` would choose 2 fewer spaces _if_ there was a trailing comma, but as above that's not really behavior we can match with the plugin (especially since the comma doesn't exist yet).

**Comment by MonkeyInWind** [comment]
thanks
