### ISSUE TITLE
Should we drop :DartAnalyzer and :Dart2JS ?

### ISSUE THREAD

**Issue by natebosch** [dart-lang/dart-vim-plugin#89]
I haven't used either of these in ages.

- `:DartAnalyzer` is currently broken. At some point the error format changed and we never updated our expectations so you get an unusable quickfix list
- Flutter users can't use either of these commands.
- For invoking dart2js we expect most end users to use `build_runner` and `build_web_compilers`.
- For analyzer the analysis server and an LSP plugin give a better experience.

@cbracken @sigmundch - Do you think there is a good reason to keep these?

**Comment by cbracken** [comment]
Assume I just +1 what @sigmundch says for `:Dart2js`. I don't do any dart2js development, but I'm assuming the current workflow generally doesn't involve direct invocation of dart2js. 

On `:DartAnalyzer` I used to use it pretty extensively, but Flutter has `flutter analyze` which also supports an optional `--watch` argument so I haven't been using it for the past couple years. For the rationale for this even with the existence of LSC, in my case, it's that I intensely dislike having live analysis in my editor and find it incredibly distracting. That's not in itself an argument against live analysis. I think it'd be sufficient and possibly even better to just make it possible to show/hide that analysis on demand.

**Comment by sigmundch** [comment]
I'm fine dropping `:dart2js` - I think it provides less value since we usually don't have anything actionable in the editor from using dart2js (also you have to be standing on the main entrypoint file for it to be useful, on any other library it's useless).

I don't use the `:dartanalyzer` command (I too rely on the lsp plugin). Given that users haven't requested that we fix the current behavior, my guess is that others aren't using it either? Since we don't have a mechanism to reach out to users, we could replace the commands with a message (maybe shown on a quickfix window) that says "the command was removed, we recommend LSP, but if you want it back, file an issue at github/.../ or +1 issue `#123`" ?

**Comment by natebosch** [comment]
@cbracken - if you are using `vim-lsc` the feature to be able to toggle diagnostics on and off is tracked at https://github.com/natebosch/vim-lsc/issues/100

**Comment by cbracken** [comment]
SGTM! For the time being, I'm just using the plugin for syntax highlighting and I've patched a version of ctags with Dart support for completion/jump to definition, which is low-tech but works for me. Will keep an eye on that issue!
