### ISSUE TITLE
Remove config option for dart_highlight_types

### ISSUE THREAD

**Issue by natebosch** [dart-lang/dart-vim-plugin#95]
See discussion in https://github.com/dart-lang/dart-vim-plugin/pull/94#discussion_r351067917

I think we should consider removing this option in the interest of having a smaller config surface area. We default to enabled, and users have another option to disable other than setting the variable. They could instead to `hi link dartTypeName Normal`.

cc @cbracken @sigmundch - do you have any thoughts?

**Comment by sigmundch** [comment]
No strong preference here. I would like us to document it clearly though. The `:help` doesn't mention dart_highlight_types, but does include dart_coretypes_highlight. 

Speaking of which, I'd also remove the flag for the coretypes.

I think the group still has value, since dartTypeName can match a lot more, but the list of core-types is a well defined list and less likely to cause trouble. Do you agree?

**Comment by natebosch** [comment]
+1 on improving the documentation for this - I can add an example in the docs about how to clear out each of these highlight groups.

+1 on removing the flag for coretypes at the same time, with the same reasoning.

+1 on keeping the core types, and the user types based on capitalization, as separate highlight groups so that users have the option of flipping them individually.


What I might do is rename some of the groups, link them all into `dartType`, then link that to `Type`. This would maintain the ability to pick and choose which to disable, and make it easy to turn off _all_ type highlighting with `hi link dartType Normal`.

Once we get a few of the other PRs settled I'll open up a new one with a proposal for this.
